### PR TITLE
add Join page

### PR DESCRIPTION
**Pull request by omarcostahamido**
please review it, make changes, and merge.

something to note: I used the dark grey i mentioned in #10 as background color here, just to try.

### CODE REVIEW

**Comment by andyyPark** [comment]
I changed it so that it looks similar to the team page. Let me know what you think!

image

**Comment by omarcostahamido** [comment]
Thank you @andyyPark .
Changed it from a draft into a "ready for review" PR.
Please confirm it and let's merge it.
Same for @TDHTTTT and @Chriscrosser3310 , if you're available.

Thank you

**Review by andyyPark — APPROVED** [review]

**Comment by TDHTTTT** [comment]
Don't you guys think the alignment is a bit weird? Maybe it could be better for the icons to aligned vertically?

**Review by TDHTTTT — COMMENTED** [review]
we need to have a consistent style across pages

**Review by Chriscrosser3310 — COMMENTED** [review]
@TDHTTTT Maybe a slightly larger separation? The last one is still not aligned:
image

**Comment by andyyPark** [comment]
Does this look better?
image

**Comment by omarcostahamido** [comment]
_ooof_, much better!
thanks @andyyPark @TDHTTTT @Chriscrosser3310 
please add the approval ✅

**Review by TDHTTTT — APPROVED** [review]
nice! let's make sure we have consistent style across page!

**Review by Chriscrosser3310 — APPROVED** [review]

**Comment by omarcostahamido** [comment]
thanks everyone 🎉

**Comment by omarcostahamido** [comment]
this fixes #7

**Pull request merged**
