### PR TITLE
Removed president tag 

### PR DESCRIPTION
**Pull request by pranavvp10**
Removed president tag from founding section. #43

### CODE REVIEW

**Review by omarcostahamido — APPROVED** [review]
Well done @pranavvp10 , this works.
This fixes #43

**Comment by omarcostahamido** [comment]
@pranavvp10 I would like to invite you to tackle one of the other [issues](https://github.com/QC-UCI/QC-UCI.github.io/issues) tagged with `good first issue` or `help wanted`

Thank you!

**Comment by pranavvp10** [comment]
Thanks for your support. :relaxed:

**Comment by omarcostahamido** [comment]
@pranavvp10 I'd also like to ask you how you found out about us.

**Comment by pranavvp10** [comment]
I think , on [https://goodfirstissues.com/](url).

**Pull request merged**
