### PR TITLE
Style tailwind contact

### PR DESCRIPTION
**Pull request by TDHTTTT**
Experimenting with tailwind css on the contact form. I adapted this [template](https://tailwindcomponents.com/component/basic-contact-form).

If you only want to see the result, you don't need to install any npm packages since everything is already in `css/tailwind_style.css`. But if you need to tweak something in `css/style.css` you need to install tailwind and postcss by:

```bash
npm install
npm run build
```

Some benefits using tailwind:

+ Write less CSS ourselves
+ Fast to experiment with style
+ Mobile ready
+ Easy to change the overall theme (e.g. dark mode) using palette 
+ Many extensions and [resources](https://github.com/aniftyco/awesome-tailwindcss) 

BTW, I have only tested the form locally and it seems to work with Formspree's API.

### CODE REVIEW

**Comment by TDHTTTT** [comment]
Screenshot_2020-10-03_13-04-17

**Comment by TDHTTTT** [comment]
Apart from directly using the class in HTML, one can also apply the styles into CSS as specified in the [doc](https://tailwindcss.com/docs/functions-and-directives#apply)

**Comment by TDHTTTT** [comment]
image
image

👆Comparison on mobile

**Comment by TDHTTTT** [comment]
BTW, `npm run build` is defined in `package.json`:
```
"build": "postcss css/style.css -o css/tailwind_style.css"
```

**Review by omarcostahamido — APPROVED** [review]
It works, I approve.
My only comment:
- added complexity. tripled the lines of code on the form, extra files, and required steps to update this page in the future. Seemed to go in contrary direction to the boilerplate discussion in #17

**Comment by omarcostahamido** [comment]
Not sure if @DanielQ56 ever got to work on the form. I'd be nice if he's able to chime in just to let us know what is the status.
Else, move forward with @andyyPark approval, and we need to make sure to say `this fixes #45 #18 `
good job

**Comment by DanielQ56** [comment]
Hi, sorry, been busy with a couple other projects currently, @andyyPark and I were planning on working on it this weekend.

**Comment by TDHTTTT** [comment]
>     * added complexity. tripled the lines of code on the form, extra files, and required steps to update this page in the future. Seemed to go in contrary direction to the boilerplate discussion in #17

@omarcostahamido 

The reason for more HTML is because the style is directly coded in the HTML class. If we want to have less HTML we can definitely use the @apply directive that Tailwind [provides](https://tailwindcss.com/docs/functions-and-directives#apply). The complexity is added at the right level IMO:
+ If we want to achieve similar staff (e.g. theme, mobile support etc.). It would require significantly more work.
+ Tailwind is much simpler compared to other frontend libraries (e.g. React).
+ If we want to take advantage of the vast resource in modern web dev, npm is definitely worthwhile

All in all, Tailwind will save us time and open up new possibility (both for style and functions) in the long run. Also, I think it is the right time to adopt Tailwind as we have a solid foundation for our website.

**Review by andyyPark — APPROVED** [review]

**Comment by andyyPark** [comment]
I love this change and lets stick with this! This fixes #45 #18

**Comment by omarcostahamido** [comment]
@andyyPark you're not doing it the right way.
It is when you merge a PR that you add the message `this fixes #xx`
When you do that it will automatically close those issues.

In any case, I appreciate the thoroughness of manually going to the issues and stating where they were fixed.
But for future merged PRs, try using this technique and save a bit of time ;)
Thanks.

**Comment by andyyPark** [comment]
Did not know that, thanks @omarcostahamido!

**Comment by TDHTTTT** [comment]
> Seemed to go in contrary direction to the boilerplate discussion in #17

@omarcostahamido 

Regarding this, I don't think that's the same "boilerplate". #17 is trying to re-use the same HTML while in order to make Tailwind CSS and future npm packages to work, the additional setup is required. The additional setup is a one-time cost: once you set it up, you don't have to worry about it in the long run while in #17, every time one adds an event, that HTML needs to be copy and pasted.

**Pull request merged**
