### PR TITLE
add Events page

### PR DESCRIPTION
**Pull request by andyyPark**
This PR goes over the event page!
image

### CODE REVIEW

**Comment by TDHTTTT** [comment]
Is it possible to change the style of the calendar to be more appealing and more consistent with our theme?

**Comment by omarcostahamido** [comment]
i'd say:
- future events ~~(where we'd include this thing for tomorrow, i.e. go copy from what @Chriscrosser3310 sent in slack)~~ (@omarcostahamido , but feel free to add more)
- google calendar (@TDHTTTT I'm not sure google lets you choose "themes", unless you want to spend some time hacking the embed code or injecting style changes?)
- past newletters ~~(@KylerFrazier )~~ (@omarcostahamido )
- past events/meetings with links to materials (@omarcostahamido )

**Comment by omarcostahamido** [comment]
huh... https://www.sitepoint.com/community/t/how-can-i-improve-the-appearance-of-embedded-google-calendar/96326

**Comment by omarcostahamido** [comment]
@andyyPark I added a lot of content, but made zero styling.
this fixes #9

**Review by omarcostahamido — APPROVED** [review]
@andyyPark I added a lot of content, but made zero styling.
you know what to do. I trust you can put it online very soon.
(approved in advance)
this fixes #9

**Comment by omarcostahamido** [comment]
we wanted to have this out today.
please make the necessary style and other changes, and make it public asap.

**Comment by andyyPark** [comment]
Sorry I will have something pushed soon. I have been working on another project which is due soon.

**Comment by Chriscrosser3310** [comment]
I have a few suggestions for styling:
1. Similar to the Team page, we can include several filters for calendars and the list of events. I propose to combine past newsletters and past events, so we can have these three: "Calendar", "Future events" and "Past events". 
2. The color of words can be changed to a lighter one (maybe white?), or simply add a white square canvas behind it (like the one behind the title "Events"). 

The overall style now may not look very appealing and consistent, but I think we can make it readable first before thinking about the appearance.

**Comment by andyyPark** [comment]
Added styling to this just like the team page
image

**Comment by omarcostahamido** [comment]
since calendar will always be there, maybe put it above or below the changing tabs.
Also, watch out for the weird behaviour that happens when you have browser a little zoomed in.

**Comment by TDHTTTT** [comment]
It would be nice to differentiate upcoming events from past events visually (maybe with color or draw a line), which might require a bit js to update it dynamically.

**Comment by TDHTTTT** [comment]
:point_up:  a hacky way to grey out all the past events, which should be fine as long as we stick to the current format of date. Feel free to tweak the past/upcoming event style!

**Comment by Chriscrosser3310** [comment]
> since calendar will always be there, maybe put it above or below the changing tabs.

I also think this is a better layout. Perhaps try it and see how it looks?

**Comment by TDHTTTT** [comment]
I just added our virtual booth to the event list

**Comment by andyyPark** [comment]
this fixes #9

**Pull request merged**
