### PR TITLE
added president tag

### PR DESCRIPTION
**Pull request by pranavvp10**
added president tag for current and previous board. @omarcostahamido  #24

### CODE REVIEW

**Comment by omarcostahamido** [comment]
hi @pranavvp10 , very good. Can I ask you to make it inside square brackets?
like: [ President ]
Also, can you make it with the color: slategrey
☝️ add this in the css, yes?

tag me again when you got it :)

Thank you.

**Comment by pranavvp10** [comment]
Sure

**Comment by omarcostahamido** [comment]
Hi @pranavvp10 when I said ` ☝️ add this in the css, yes? ` I was referring to the [style.css file](https://github.com/QC-UCI/QC-UCI.github.io/blob/master/css/style.css).
The reason for that is that it will make it easier to update the color when our designer tries new color schemes.
If you come up with a new name, make sure to follow the same style of double underscore notation to be consistent with what is there already.

Besides that nothing else: this is looking good.

**Review by omarcostahamido — CHANGES_REQUESTED** [review]
Hi @pranavvp10 when I said `☝️ add this in the css, yes? ` I was referring to the style.css file.
The reason for that is that it will make it easier to update the color when our designer tries new color schemes.
If you come up with a new name, make sure to follow the same style of double underscore notation to be consistent with what is there already.

Besides that nothing else: this is looking good.

**Comment by pranavvp10** [comment]
Hey @omarcostahamido  I have made the changes you  requested (https://github.com/QC-UCI/QC-UCI.github.io/pull/40#pullrequestreview-497351353 ). please review it and I will make  any changes if needed. 
Thanks for pointing out the previous inline CSS problem.

**Review by omarcostahamido — APPROVED** [review]
super.
thank you for this contribution @pranavvp10

**Comment by omarcostahamido** [comment]
@all-contributors please add @pranavvp10  for code

**Pull request merged**
