### PR TITLE
Embed qc@uci video

### PR DESCRIPTION
**Pull request by andyyPark**
This PR addresses #41 and #28. Below is the screenshot of the new index page.
image

### CODE REVIEW

**Review by omarcostahamido — APPROVED** [review]
not sure why you went ahead and added tailwind_style.css to all pages already.
And you're actually not using it here, right?
This works.
I'll just have some idea for future work/improvements:
- make it larger
- make it autoplay muted on page load

You can work on it already before merging, if you want.
Or merge it already.

Approved.

**Comment by TDHTTTT** [comment]
> not sure why you went ahead and added tailwind_style.css to all pages already.

I think it is because for some reason the Tailwind css is affecting the size of a box and it might just be easier to have all pages have the same effect to keep it consistent,

**Comment by andyyPark** [comment]
> I'll just have some idea for future work/improvements:
> 
> * make it larger
> * make it autoplay muted on page load

Make it larger as in make the embedded youtube larger?

**Comment by omarcostahamido** [comment]
@TDHTTTT 
copy that
@andyyPark 
Yes. Just an idea to try.

I think I would like to see the homepage turning into something [like this](http://alp.uci.edu/).
:)

**Comment by andyyPark** [comment]
I made the video a little larger. I will merge it for now and get back to it.

**Pull request merged**
