### PR TITLE
Contact Us

### PR DESCRIPTION
**Pull request by DanielQ56**
Changed to the form idea so here's just the blank Contact Us page that's linked to the homepage.

### CODE REVIEW

**Comment by Chriscrosser3310** [comment]
I'm not sure but wouldn't this be duplicate to the "Join" page (#11 )?

**Comment by andyyPark** [comment]
This page will have a few icons used in the join page and a form as well @Chriscrosser3310

**Comment by omarcostahamido** [comment]
the form is not here yet, correct?
At least I don't see it.

**Comment by andyyPark** [comment]
Correct its not up yet

**Comment by omarcostahamido** [comment]
@DanielQ56 is this ready to be merged?

**Comment by omarcostahamido** [comment]
I can see that you used formspree.io.
Did you create an account with quantumcomputing@uci.edu?
I just logged into the email account and I don't see there anything related to this.
I assume it is necessary to register and verify the email address before being able to use this. (?)

I also noticed that the free account of formspree.io is limited to 50 contacts per month...

If we are going this way we definitely need a reCAPTCHA to avoid bots using all the limited available submissions.

**edit:** just use `required=""` for all required fields. the script you wrote is actually preventing the form from being submitted.

this needs to be run one time from within the domain qc-club.com in order to be activated from there. An activation email with be sent to quantumcomputing@uci.edu.

Shortly after that is done we need to assess the reCAPTCHA situation asap.

**Comment by omarcostahamido** [comment]
@andyyPark please review the style together with @DanielQ56 .
Then let's merge and activate.

**Comment by omarcostahamido** [comment]
@DanielQ56 noticed that you tried pushing some changes with #60f0261 before fetching my commit.
And yeah, I commented out that function call on the js but we can get rid of that file entirely.

Also noticed some new css. I like the larger font.
Are we ready to merge and activate?

**Comment by DanielQ56** [comment]
@omarcostahamido yeah didn't realize you pushed something earlier but resolved it. And yeah should be ready to merge and activate. I can add more specialized css later but just wanted to get it somewhat responsive/readable for now.

**Comment by omarcostahamido** [comment]
Leggo!

**Comment by omarcostahamido** [comment]
activated!

**Comment by omarcostahamido** [comment]
@DanielQ56 I created a new issue [here](https://github.com/QC-UCI/QC-UCI.github.io/issues/18) for you to follow up on the work you mentioned.
In the meantime I'd like to invite you to take a look at the other pages/PRs, take a look at the issues, and even check out the discussion on the closed issue [here](https://github.com/QC-UCI/QC-UCI.github.io/issues/13).

Good job on this one,
O

**Pull request merged**
