### PR TITLE
Add design to footer

### PR DESCRIPTION
**Pull request by andyyPark**
Added some styling to the existing footer. Below shows what it looks like!
image

### CODE REVIEW

**Review by omarcostahamido — CHANGES_REQUESTED** [review]
Kind of an overkill footer implementation. 
The more so that you don't add it to the index page: and by definition a footer is everywhere.
The extra information also becomes somewhat redundant on the join and contact page.
I would actually prefer going the other direction of making it more discreet as possible.

**Comment by omarcostahamido** [comment]
this refers to #19

**Comment by omarcostahamido** [comment]
my suggestion:
- remove everything above the --------------
- keep everything below the ----------- including the line itself
- hyperlink QC@UCI to go to contact page
- get rid of white background
- turn text to white, or a light gray
- play around with the dimension of the ------------- to make it play well with all pages

:)

**Comment by andyyPark** [comment]
@omarcostahamido just changed it!

**Review by omarcostahamido — APPROVED** [review]
looks good!

**Comment by andyyPark** [comment]
this fixes #19

**Pull request merged**
