### PR TITLE
added how to set up Tailwind locally

### LINKED ISSUE #53: documentation in readme about Tailwind
Just realized I need to provide some setup info in readme. I am working on it.

### PR DESCRIPTION
**Pull request by TDHTTTT**
Fixing #53

### CODE REVIEW

**Review by andyyPark — COMMENTED** [review]
Can you delete the todo section since we are pretty much done with the boilerplate?

**Comment by TDHTTTT** [comment]
done

**Comment by andyyPark** [comment]
Thank you!

**Comment by andyyPark** [comment]
This fixes #53

**Comment by omarcostahamido** [comment]
@andyyPark lol, still not auto closing the issue.
you need to edit the message when merging ;)

**Comment by andyyPark** [comment]
@omarcostahamido I did what you told me in #48. What message do I have to edit when merging?

**Comment by omarcostahamido** [comment]
Let me see if I can give you an example.

**Comment by omarcostahamido** [comment]
@andyyPark see here: https://drive.google.com/file/d/1aSN6NyU00V3bpPEccYiP_h9ImvEpBd14/view?usp=sharing

**Comment by andyyPark** [comment]
@omarcostahamido Cool, I got it!

**Pull request merged**
